language: python

sudo: false

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

deploy:
  provider: script
  script: bash scripts/push.sh
  on:
    branch: master
