language: bash

install:
  - echo "no install."

script:
  - echo "no script."

before_deploy:
  pip install --user awscli

deploy:
  - provider: script
    skip_cleanup: true
    script: ~/.local/bin/aws s3 sync public/www.tranenterprises.org s3://www.tranenterprises.org/ --delete
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: ~/.local/bin/aws s3 sync public/www.robert.tranenterprises.org s3://www.robert.tranenterprises.org/ --delete
    on:
      branch: master
