language: python

install:
  - echo "no install."

script:
  - echo "no script."

deploy:
  provider: script
  script:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    - bash scripts/push.sh
  on:
    branch: master
